{% set name = "airflow-config" %}
{% set version = "1.10.7" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-config/airflow_config-{{ version }}.tar.gz
  sha256: 704d50ce1337da70a0ac6049539d284bebe46399d330a8e28ef3c312b2cad52c

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-jupyter-builder
    - nodejs
    - pip
    - pnpm
  run:
    - python >={{ python_min }}
    - airflow-pydantic >=1.2,<1.3
    - apache-airflow >=2.8,<3
    - colorlog
    - hydra-core
    - jinja2
    - omegaconf
    - pydantic >=2

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_config

about:
  home: https://github.com/airflow-laminar/airflow-config
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Airflow utilities for configuration of many DAGs and DAG environments
  description: Airflow utilities for configuration of many DAGs and DAG environments
  dev_url: https://github.com/airflow-laminar/airflow-config

extra:
  recipe-maintainers:
    - timkpaine
