{% set name = "airflow-config" %}
{% set version = "1.5.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-config/airflow_config-{{ version }}.tar.gz
  sha256: c4c8ae87b466309d1a5bc679e9974b2e1b7b9781c6e0ec214043c347549bfac6

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - airflow-pydantic >=0.3.0,<1
    - apache-airflow >=2.8,<3
    - colorlog
    - hydra-core
    - jinja2
    - omegaconf
    - pydantic >=2

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_config

about:
  home: https://github.com/airflow-laminar/airflow-config
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Airflow utilities for configuration of many DAGs and DAG environments
  description: Airflow utilities for configuration of many DAGs and DAG environments
  dev_url: https://github.com/airflow-laminar/airflow-config

extra:
  recipe-maintainers:
    - timkpaine
