{% set name = "airflow-config" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/airflow-config/airflow_config-{{ version }}.tar.gz
  sha256: 54f498daf486c757dbbbee9a0778eebb45e6d61c8bd3108677d4be2f4d4f001f

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - apache-airflow >=2.8,<3
    - hydra-core
    - jinja2
    - omegaconf
    - pydantic >=2

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - airflow_config

about:
  home: https://github.com/airflow-laminar/airflow-config
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Airflow utilities for configuration of many DAGs and DAG environments
  description: Airflow utilities for configuration of many DAGs and DAG environments
  dev_url: https://github.com/airflow-laminar/airflow-config

extra:
  recipe-maintainers:
    - timkpaine
