schema_version: 1

context:
  name: airflow-config
  version: "1.12.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-config/airflow_config-${{ version }}.tar.gz
  sha256: 801422821b3f3775846ba3466092e4056c9e1a87f590db6c5b2495f2dcc6907b

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-js
    - nodejs
    - pip
    - pnpm
  run:
    - python >=${{ python_min }}
    - airflow-pydantic >=1.6,<1.8
    - colorlog
    - hydra-core
    - jinja2
    - omegaconf
    - pydantic >=2

tests:
  - python:
      imports:
        - airflow_config
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Airflow utilities for configuration of many DAGs and DAG environments
  description: Airflow utilities for configuration of many DAGs and DAG environments
  homepage: https://github.com/airflow-laminar/airflow-config
  repository: https://github.com/airflow-laminar/airflow-config

extra:
  recipe-maintainers:
    - timkpaine
